[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer_runs = 200
via_ir = true
remappings = [
    '@oasisprotocol/sapphire-contracts/=dependencies/@oasisprotocol-sapphire-contracts-latest/',
    '@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/',
    'forge-std/=dependencies/forge-std-1.9.5/src/',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[dependencies]
forge-std = "1.9.5"
"@openzeppelin-contracts" = "5.2.0"
"@oasisprotocol/sapphire-contracts" = { version = "latest", git = "https://github.com/oasisprotocol/sapphire-paratime.git", rev = "352eb6a34b8750dbf32512df0d68cfaf81025ea5" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
